version: 2.1

jobs:
  build:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run: apt-get update && apt-get install -y g++
  test:
    steps:
      - checkout
      - run: g++ -std=c++2a ./src/test.cpp

workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
